general.import = [
    "~/.config/alacritty/RCW-120-V1.toml"
]

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[window]
dynamic_title = true
opacity = 1
title = "Alacritty"
padding.x = 4
padding.y = 4

[window.class]
general = "Alacritty"
instance = "Alacritty"
