import = [
    "~/.config/alacritty/themes/themes/RCW-120-V1.toml"
]

[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
