general.import = [
    "~/.config/alacritty/RCW-120-V1.toml"
]

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "normal"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[window]
dynamic_title = true
opacity = 0.55
title = "Alacritty"
padding.x = 0
padding.y = 0

[window.class]
general = "Alacritty"
instance = "Alacritty"
