#! /bin/bash

#  _
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

setxkbmap -layout "us,ru" -variant qwerty -option grp:win_space_toggle
pgrep -x sxhkd > /dev/null || sxhkd &

# enable picture-in-picture
bspc rule -a '*:*:Picture-in-Picture' state=floating

# workspaces & monitors
bspc wm -O *HDMI-A-0 DisplayPort-0
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 
bspc monitor DisplayPort-0 -d 9 10

bspc config split_ratio          0.52

# window borders (Auto-Generate)
bspc config border_width 1
bspc config normal_border_color "#211E2F"
bspc config focused_border_color "#53ffb1"
bspc config active_border_color "#54BEBD"
bspc config presel_feedback_color "#915FFF"

# gaps
bspc config gapless_monocle false
bspc config window_gap 0
bspc config gapless_monocle      true

# monocle
bspc config borderless_monocle true
bspc config pointer_modifier    super

# focusing window on cursor hover
#bspc config focus_follows_pointer true
bspc config pointer_modifier    super

# scripts
~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh &

# launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# launch compositor
picom --config ~/.config/bspwm/picom_configurations/1.conf &

# autostart
openrgb -p Emerald
flameshot &
bluetooth-autoconnect &

