#! /bin/sh

setxkbmap -layout "us,ru" -variant qwerty -option grp:win_space_toggle
pgrep -x sxhkd > /dev/null || sxhkd &

# enable picture-in-picture
bspc rule -a '*:*:Picture-in-Picture' state=floating

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8

########### visual

bspc config split_ratio          0.52

# window borders (Auto-Generate)
bspc config focused_border_color "#53FFB1"
bspc config normal_border_color "#211E2F"
bspc config border_width 2
bspc config borderless_monocle true
bspc config active_border_color "#54BEBD"
bspc config presel_feedback_color "#6272a4"

# gaps
bspc config gapless_monocle false
bspc config window_gap 8 
bspc config gapless_monocle      true

# scripts

~/.config/bspwm/scripts/launch.sh &
~/.config/polybar/launch.sh &

# launch notification daemon

dunst -config $HOME/.config/bspwm/dunstrc &

# launch compositor

picom --config ~/.config/bspwm/picom_configurations/1.conf &

# blueberry tray service

blueberry-tray &

# autostart
flameshot &


